# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Megan E. McDonnell
description: >- # this means to ignore newlines until "baseurl:"
  lorem ipsum description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meganmcd13.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "meganmcd13.github.io"

author:
  name: Megan E. McDonnell
  email: "mmcdonnell@cmu.edu"

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: auto
  social_links:
    - { platform: github,         user_url: "https://github.com/meganmcd13" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=6O-C7SEAAAAJ" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/megan-mcdonnell13/" }

header_pages:
  - projects.markdown
  - skills.markdown
  - hobbies.markdown

# Build settings
ignore_theme_config: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima

sass:
  quiet_deps: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
